name = "panel-facturacion"
main = "worker.js"
compatibility_date = "2024-11-06"

# Sirve los archivos estáticos (index.html) desde la raíz del repositorio
[assets]
directory = "."
binding = "ASSETS"

# Base de datos KV. Reemplaza el id por el de tu namespace "panel-facturacion".
[[kv_namespaces]]
binding = "PANEL"
id = 14e37889d27e40548e02da8895b3af26
